name: Deploy to Azure Static Web Apps

on:
  workflow_run:
    workflows:
      - Test Before Deployment # Matches the name in test-before-deploy.yml
    types:
      - completed

permissions:
  id-token: write
  contents: read

jobs:
  deploy-testing:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Set Environment Variable for Testing
        run: echo "ENVIRONMENT=testing" >> $GITHUB_ENV
      - name: Inject Environment Variable into HTML
        run: |
          sed -i "s/{{ ENVIRONMENT }}/$ENVIRONMENT/" index.html
      - name: Debug Environment Variables
        run: env
      - name: Debug HTML File
        run: cat index.html
      - name: Deploy to Testing
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_TESTING }}
          app_location: "."
          output_location: ""
          deployment_action: "upload"

  deploy-staging:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    needs: deploy-testing
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Set Environment Variable for Staging
        run: echo "ENVIRONMENT=staging" >> $GITHUB_ENV
      - name: Inject Environment Variable into HTML
        run: |
          sed -i "s/{{ ENVIRONMENT }}/$ENVIRONMENT/" index.html
      - name: Debug Environment Variables
        run: env
      - name: Debug HTML File
        run: cat index.html
      - name: Deploy to Staging
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_STAGING }}
          app_location: "."
          output_location: ""
          deployment_action: "upload"

  deploy-production:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    needs: deploy-staging
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Set Environment Variable for Production
        run: echo "ENVIRONMENT=production" >> $GITHUB_ENV
      - name: Inject Environment Variable into HTML
        run: |
          sed -i "s/{{ ENVIRONMENT }}/$ENVIRONMENT/" index.html
      - name: Debug Environment Variables
        run: env
      - name: Debug HTML File
        run: cat index.html
      - name: Deploy to Production
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_PRODUCTION }}
          app_location: "."
          output_location: ""
          deployment_action: "upload"
      - name: Confirm Deployment to Production
        if: ${{ success() }}
        run: echo "Deployment to production environment succeeded!"
