name: Deployment Notifications

on:
  workflow_run:
    workflows:
      - Deploy to Azure Static Web Apps  # Must match the name in deploy.yml
    types:
      - completed

permissions:
  contents: read

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Notify on Success
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        run: echo "Deployment succeeded! Sending success notification..."

      - name: Notify on Failure
        if: ${{ github.event.workflow_run.conclusion == 'failure' }}
        run: echo "Deployment failed! Sending failure notification..."
